service: image-analysis
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  img-analysis:
    handler: index.main
    events:
      - http:
          path: /analyse
          method: get
